<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <TargetFramework>net10.0</TargetFramework>        
      <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="MethodInlining.fs" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Update="FSharp.Core" Version="10.1.302" />
    </ItemGroup>

</Project>
